--- 
- name: Update all packages
  apt:
    name: "*"
    state: latest
    update_cache: yes
    force_apt_get: yes

- name: Install NGINX 
  apt:
    name: nginx 
    state: latest
    update_cache: yes 
  notify: 
    - Started and Enabled NGINX

- name: Install MariaDB
  apt:
    name: "{{ debian_mariadb }}"
    state: latest
    update_cache: yes

- name: Install PHP-FPM
  apt: 
    name: "{{ debian_php_fpm }}"
    state: latest
    update_cache: yes
    